<?php

/**
 * @file
 * Module file for drupalx_gin.
 */

/**
 * Implements hook_page_attachments().
 */
function drupalx_gin_page_attachments(array &$attachments) {
  // Check if the current page matches the specified pattern.
  $current_path = \Drupal::service('path.current')->getPath();
  if (preg_match('/^\/node\/\d+\/layout$/', $current_path)) {

    // Add the drupalx_gin library to the page attachments.
    $attachments['#attached']['library'][] = 'drupalx_gin/drupalx_gin';
  }
}
